### ISSUE TITLE
Warlord FFA Failed to Start

### ISSUE THREAD

**Issue by chrisdutrow** [triplea-maps/red_sun_over_china#17]
Map
red_sun_over_china

Log Message
Failed to start game

TripleA Version
2.5.22294

Java Version
11.0.6

Operating System
Windows 10

Memory
Heap utilization statistics [MB]
Used Memory: 382
Free memory: 1596
Total memory: 1979
Max memory: 1979

Stack Trace
Exception: java.lang.IllegalStateExceptionNo data of type centers for territory: Korea-Mukden-Korea
No data of type centers for territory: Korea-Mukden-Mukden
No data of type centers for territory: Port Arthur-Mukden-Port Arthur
No data of type centers for territory: Port Arthur-Mukden-Mukden
No data of type centers for territory: Mukden-Peking-Mukden
No data of type centers for territory: Mukden-Peking-Peking
No data of type centers for territory: Peking-Tsinan-Peking
No data of type centers for territory: Peking-Tsinan-Tsinan
No data of type centers for territory: Peking-Taiyuan-Peking
No data of type centers for territory: Peking-Taiyuan-Taiyuan
No data of type centers for territory: Peking-Sian-Peking
No data of type centers for territory: Peking-Sian-Sian
No data of type centers for territory: Peking-Wuhan-Peking
No data of type centers for territory: Peking-Wuhan-Wuhan
No data of type centers for territory: Taiyuan-Sian-Taiyuan
No data of type centers for territory: Taiyuan-Sian-Sian
No data of type centers for territory: Taiyuan-Wuhan-Taiyuan
No data of type centers for territory: Taiyuan-Wuhan-Wuhan
No data of type centers for territory: Taiyuan-Tsinan-Taiyuan
No data of type centers for territory: Taiyuan-Tsinan-Tsinan
No data of type centers for territory: Sian-Tsinan-Sian
No data of type centers for territory: Sian-Tsinan-Tsinan
No data of type centers for territory: Sian-Wuhan-Sian
No data of type centers for territory: Sian-Wuhan-Wuhan
No data of type centers for territory: Wuhan-Tsinan-Wuhan
No data of type centers for territory: Wuhan-Tsinan-Tsinan
No data of type centers for territory: Tsinan-Tsingtao-Tsinan
No data of type centers for territory: Tsinan-Tsingtao-Tsingtao
No data of type centers for territory: Tsinan-Nanking-Tsinan
No data of type centers for territory: Tsinan-Nanking-Nanking
No data of type centers for territory: Nanking-Shanghai-Nanking
No data of type centers for territory: Nanking-Shanghai-Shanghai
No data of type centers for territory: Shanghai-Nanchang-Shanghai
No data of type centers for territory: Shanghai-Nanchang-Nanchang
No data of type centers for territory: Nanchang-Changsha-Nanchang
No data of type centers for territory: Nanchang-Changsha-Changsha
No data of type centers for territory: Wuhan-Changsha-Wuhan
No data of type centers for territory: Wuhan-Changsha-Changsha
No data of type centers for territory: Changsha-Canton-Changsha
No data of type centers for territory: Changsha-Canton-Canton
No data of type centers for territory: Changsha-Kweiyang-Changsha
No data of type centers for territory: Changsha-Kweiyang-Kweiyang
No data of type centers for territory: Canton-Kweiyang-Canton
No data of type centers for territory: Canton-Kweiyang-Kweiyang
No data of type centers for territory: Lanchow-Sian-Lanchow
No data of type centers for territory: Lanchow-Sian-Sian
No data of type centers for territory: Lanchow-Chungking-Lanchow
No data of type centers for territory: Lanchow-Chungking-Chungking
No data of type centers for territory: Sian-Chungking-Sian
No data of type centers for territory: Sian-Chungking-Chungking
No data of type centers for territory: Chungking-Kweiyang-Chungking
No data of type centers for territory: Chungking-Kweiyang-Kweiyang
No data of type centers for territory: Chungking-Kunming-Chungking
No data of type centers for territory: Chungking-Kunming-Kunming
No data of type centers for territory: Kunming-Kweiyang-Kunming
No data of type centers for territory: Kunming-Kweiyang-Kweiyang
No data of type centers for territory: Kunming-Hanoi-Kunming
No data of type centers for territory: Kunming-Hanoi-Hanoi
No data of type centers for territory: Hanoi-Nanning-Hanoi
No data of type centers for territory: Hanoi-Nanning-Nanning
No data of type centers for territory: Hanoi-Bangkok-Hanoi
No data of type centers for territory: Hanoi-Bangkok-Bangkok
No data of type centers for territory: Bangkok-Rangoon-Bangkok
No data of type centers for territory: Bangkok-Rangoon-Rangoon
No data of type centers for territory: Calcutta-East Assam-Calcutta
No data of type centers for territory: Calcutta-East Assam-East Assam
No data of type centers for territory: Calcutta-Chittagong-Calcutta
No data of type centers for territory: Calcutta-Chittagong-Chittagong
No data of type centers for territory: East Assam-Chittagong-East Assam
No data of type centers for territory: East Assam-Chittagong-Chittagong

java.lang.Exception
	at games.strategy.triplea.ui.mapdata.MapData.verifyKeys(MapData.java:548)
	at games.strategy.triplea.ui.mapdata.MapData.verify(MapData.java:514)
	at games.strategy.triplea.ui.TripleAFrame.create(TripleAFrame.java:686)
	at games.strategy.engine.framework.startup.mc.HeadedLaunchAction.startGame(HeadedLaunchAction.java:64)
	at games.strategy.triplea.TripleA.startGame(TripleA.java:62)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.loadGame(LocalLauncher.java:68)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launch(LocalLauncher.java:55)
	at games.strategy.engine.framework.startup.ui.panels.main.MainPanelBuilder.lambda$buildMainPanel$0(MainPanelBuilder.java:46)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by RogerCooper** [comment]
I will take a look at this over the weekend.


-----Original Message-----
From: chrisdutrow ***@***.***>
To: triplea-maps/red_sun_over_china ***@***.***>
Cc: Subscribed ***@***.***>
Sent: Thu, Feb 17, 2022 2:08 pm
Subject: [triplea-maps/red_sun_over_china] Warlord FFA Failed to Start (Issue #17)

Map
red_sun_over_chinaLog Message
Failed to start gameTripleA Version
2.5.22294Java Version
11.0.6Operating System
Windows 10Memory
Heap utilization statistics [MB]
Used Memory: 382
Free memory: 1596
Total memory: 1979
Max memory: 1979Stack Trace
Exception: java.lang.IllegalStateExceptionNo data of type centers for territory: Korea-Mukden-Korea
No data of type centers for territory: Korea-Mukden-Mukden
No data of type centers for territory: Port Arthur-Mukden-Port Arthur
No data of type centers for territory: Port Arthur-Mukden-Mukden
No data of type centers for territory: Mukden-Peking-Mukden
No data of type centers for territory: Mukden-Peking-Peking
No data of type centers for territory: Peking-Tsinan-Peking
No data of type centers for territory: Peking-Tsinan-Tsinan
No data of type centers for territory: Peking-Taiyuan-Peking
No data of type centers for territory: Peking-Taiyuan-Taiyuan
No data of type centers for territory: Peking-Sian-Peking
No data of type centers for territory: Peking-Sian-Sian
No data of type centers for territory: Peking-Wuhan-Peking
No data of type centers for territory: Peking-Wuhan-Wuhan
No data of type centers for territory: Taiyuan-Sian-Taiyuan
No data of type centers for territory: Taiyuan-Sian-Sian
No data of type centers for territory: Taiyuan-Wuhan-Taiyuan
No data of type centers for territory: Taiyuan-Wuhan-Wuhan
No data of type centers for territory: Taiyuan-Tsinan-Taiyuan
No data of type centers for territory: Taiyuan-Tsinan-Tsinan
No data of type centers for territory: Sian-Tsinan-Sian
No data of type centers for territory: Sian-Tsinan-Tsinan
No data of type centers for territory: Sian-Wuhan-Sian
No data of type centers for territory: Sian-Wuhan-Wuhan
No data of type centers for territory: Wuhan-Tsinan-Wuhan
No data of type centers for territory: Wuhan-Tsinan-Tsinan
No data of type centers for territory: Tsinan-Tsingtao-Tsinan
No data of type centers for territory: Tsinan-Tsingtao-Tsingtao
No data of type centers for territory: Tsinan-Nanking-Tsinan
No data of type centers for territory: Tsinan-Nanking-Nanking
No data of type centers for territory: Nanking-Shanghai-Nanking
No data of type centers for territory: Nanking-Shanghai-Shanghai
No data of type centers for territory: Shanghai-Nanchang-Shanghai
No data of type centers for territory: Shanghai-Nanchang-Nanchang
No data of type centers for territory: Nanchang-Changsha-Nanchang
No data of type centers for territory: Nanchang-Changsha-Changsha
No data of type centers for territory: Wuhan-Changsha-Wuhan
No data of type centers for territory: Wuhan-Changsha-Changsha
No data of type centers for territory: Changsha-Canton-Changsha
No data of type centers for territory: Changsha-Canton-Canton
No data of type centers for territory: Changsha-Kweiyang-Changsha
No data of type centers for territory: Changsha-Kweiyang-Kweiyang
No data of type centers for territory: Canton-Kweiyang-Canton
No data of type centers for territory: Canton-Kweiyang-Kweiyang
No data of type centers for territory: Lanchow-Sian-Lanchow
No data of type centers for territory: Lanchow-Sian-Sian
No data of type centers for territory: Lanchow-Chungking-Lanchow
No data of type centers for territory: Lanchow-Chungking-Chungking
No data of type centers for territory: Sian-Chungking-Sian
No data of type centers for territory: Sian-Chungking-Chungking
No data of type centers for territory: Chungking-Kweiyang-Chungking
No data of type centers for territory: Chungking-Kweiyang-Kweiyang
No data of type centers for territory: Chungking-Kunming-Chungking
No data of type centers for territory: Chungking-Kunming-Kunming
No data of type centers for territory: Kunming-Kweiyang-Kunming
No data of type centers for territory: Kunming-Kweiyang-Kweiyang
No data of type centers for territory: Kunming-Hanoi-Kunming
No data of type centers for territory: Kunming-Hanoi-Hanoi
No data of type centers for territory: Hanoi-Nanning-Hanoi
No data of type centers for territory: Hanoi-Nanning-Nanning
No data of type centers for territory: Hanoi-Bangkok-Hanoi
No data of type centers for territory: Hanoi-Bangkok-Bangkok
No data of type centers for territory: Bangkok-Rangoon-Bangkok
No data of type centers for territory: Bangkok-Rangoon-Rangoon
No data of type centers for territory: Calcutta-East Assam-Calcutta
No data of type centers for territory: Calcutta-East Assam-East Assam
No data of type centers for territory: Calcutta-Chittagong-Calcutta
No data of type centers for territory: Calcutta-Chittagong-Chittagong
No data of type centers for territory: East Assam-Chittagong-East Assam
No data of type centers for territory: East Assam-Chittagong-Chittagongjava.lang.Exception
at games.strategy.triplea.ui.mapdata.MapData.verifyKeys(MapData.java:548)
at games.strategy.triplea.ui.mapdata.MapData.verify(MapData.java:514)
at games.strategy.triplea.ui.TripleAFrame.create(TripleAFrame.java:686)
at games.strategy.engine.framework.startup.mc.HeadedLaunchAction.startGame(HeadedLaunchAction.java:64)
at games.strategy.triplea.TripleA.startGame(TripleA.java:62)
at games.strategy.engine.framework.startup.launcher.LocalLauncher.loadGame(LocalLauncher.java:68)
at games.strategy.engine.framework.startup.launcher.LocalLauncher.launch(LocalLauncher.java:55)
at games.strategy.engine.framework.startup.ui.panels.main.MainPanelBuilder.lambda$buildMainPanel$0(MainPanelBuilder.java:46)
at java.base/java.lang.Thread.run(Thread.java:834)—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by RogerCooper** [comment]
I see what the problem is. The mod uses nominal territories as "auxiliary stations" for train connections, which treated as canals in the game. I will contact Pulicat and if that fails try to fix it myself.

**Comment by chrisdutrow** [comment]
Sounds good!! I appreciate the time.

**Comment by RogerCooper** [comment]
I had comment out everything about trains to get things to work. I will post that. 

I see that trains are handled differently in the Red Sun Over China scenario. Probably trains could be fixed by using the code from Red Sun Over China, but I am not particularly interested in Warlords FFA, so I am only doing the minimum to make it run (I don't like pure FFA scenarios). 

An even simpler fix would to eliminate trainlines entirely and just have train stations give a movement bonus. Let me know if you think that would improve the scenario.

**Comment by doctored** [comment]
sorry dumb question what is FFA?

**Comment by chrisdutrow** [comment]
FFA= Free For All. Honest question. All good!!

**Comment by chrisdutrow** [comment]
> I had comment out everything about trains to get things to work. I will post that.
> 
> I see that trains are handled differently in the Red Sun Over China scenario. Probably trains could be fixed by using the code from Red Sun Over China, but I am not particularly interested in Warlords FFA, so I am only doing the minimum to make it run (I don't like pure FFA scenarios).
> 
> An even simpler fix would to eliminate trainlines entirely and just have train stations give a movement bonus. Let me know if you think that would improve the scenario.

I think that would be a good fix!! Trains arent as necessary in that mode as its going to be a naturally slower game. Should I delete the trains in the xml? Is that enough to run it? Thanks.

**Comment by chrisdutrow** [comment]
Okay. So deleting rail connections/canals, and any other rail related map attribute did the trick just as you said!! I appreciate it a TON. I have been wanting to play this map for a year now and having this solution made my week!! Thank you RogerCooper for taking the time to figure this out!! :)

**Comment by doctored** [comment]
> FFA= Free For All. Honest question. All good!!

oh yeah duh :P it was early my brain wasn't working too gud :P

**Comment by RogerCooper** [comment]
I am working on train stations giving a move bonus.
